IMAGE_NAME = "bento/ubuntu-20.04"
N = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.synced_folder "/srv/nfs4/pdata", "/srv/pdata",
      type: "nfs",
      nfs_version: 4,
      nfs_udp: false,
      linux__nfs_options: ['rw','no_subtree_check','all_squash','async']
    config.vm.synced_folder "/srv/nfs4/tdata", "/srv/tdata",
      type: "nfs",
      nfs_version: 4,
      nfs_udp: false,
      linux__nfs_options: ['rw','no_subtree_check','all_squash','async']
    config.vm.synced_folder "/srv/nfs4/mdata", "/srv/mdata",
      type: "nfs",
      nfs_version: 4,
      nfs_udp: false,
      linux__nfs_options: ['rw','no_subtree_check','all_squash','async']
      #mount_options: ['actimeo=2']
    ## This is for network connectivity with host (DHCP)
    ## This should prompt with option of available interfaces
     config.vm.network "public_network"

    config.vm.provider "virtualbox" do |v|
        v.memory = 2024
        v.cpus = 2
    end

    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.50.10"
        # Set static IP - if needed
        #config.vm.network "public_network", ip: "192.168.1.10"
        master.vm.hostname = "k8s-master"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "kubernetes-setup/master-playbook.yml"
            ansible.extra_vars = {
                node_ip: "192.168.50.10",
            }
        end
    end

    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{i + 10}"
            node.vm.hostname = "node-#{i}"
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "kubernetes-setup/node-playbook.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.50.#{i + 10}",
                }
            end
        end
    end

end